In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df=pd.read_excel("/content/P670-dataset.xlsx")

In [ ]:
print(df.head)

<bound method NDFrame.head of       Unnamed: 0 state      area.code  account.length voice.plan  \
0              1    KS  area_code_415             128        yes
1              2    OH  area_code_415             107        yes
2              3    NJ  area_code_415             137         no
3              4    OH  area_code_408              84         no
4              5    OK  area_code_415              75         no
...          ...   ...            ...             ...        ...
4995        4996    HI  area_code_408              50        yes
4996        4997    WV  area_code_415             152         no
4997        4998    DC  area_code_415              61         no
4998        4999    DC  area_code_510             109         no
4999        5000    VT  area_code_415              86        yes

      voice.messages intl.plan  intl.mins  intl.calls  intl.charge  ...  \
0                 25        no       10.0           3         2.70  ...
1                 26        no       13.7           3         3.70  ...
2                  0        no       12.2           5         3.29  ...
3                  0       yes        6.6           7         1.78  ...
4                  0       yes       10.1           3         2.73  ...
...              ...       ...        ...         ...          ...  ...
4995              40        no        9.9           5         2.67  ...
4996               0        no       14.7           2         3.97  ...
4997               0        no       13.6           4         3.67  ...
4998               0        no        8.5           6         2.30  ...
4999              34        no        9.3          16         2.51  ...

      day.calls  day.charge eve.mins eve.calls  eve.charge  night.mins  \
0           110       45.07    197.4        99       16.78       244.7
1           123       27.47    195.5       103       16.62       254.4
2           114       41.38    121.2       110       10.30       162.6
3            71        50.9     61.9        88        5.26       196.9
4           113       28.34    148.3       122       12.61       186.9
...         ...         ...      ...       ...         ...         ...
4995        127       40.07      223       126       18.96       297.5
4996         90       31.31    256.8        73       21.83       213.6
4997         89        23.9    172.8       128       14.69       212.4
4998         67        32.1    171.7        92       14.59       224.4
4999        102          22    267.1       104       22.70       154.8

      night.calls  night.charge  customer.calls  churn
0              91         11.01               1     no
1             103         11.45               1     no
2             104          7.32               0     no
3              89          8.86               2     no
4             121          8.41               3     no
...           ...           ...             ...    ...
4995          116         13.39               2     no
4996          113          9.61               3    yes
4997           97          9.56               1     no
4998           89         10.10               0     no
4999          100          6.97               0     no

[5000 rows x 21 columns]>

In [ ]:
df.describe()

,Unnamed: 0,account.length,voice.messages,intl.mins,intl.calls,intl.charge,day.mins,day.calls,eve.calls,eve.charge,night.mins,night.calls,night.charge,customer.calls
count,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,100.25860,7.755200,10.261780,4.435200,2.771196,180.288900,100.029400,100.191000,17.054322,200.391620,99.919200,9.017732,1.570400
std,1443.520003,39.69456,13.546393,2.761396,2.456788,0.745514,53.894699,19.831197,19.826496,4.296843,50.527789,19.958686,2.273763,1.306363
min,1.000000,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1250.750000,73.00000,0.000000,8.500000,3.000000,2.300000,143.700000,87.000000,87.000000,14.140000,166.900000,87.000000,7.510000,1.000000
50%,2500.500000,100.00000,0.000000,10.300000,4.000000,2.780000,180.100000,100.000000,100.000000,17.090000,200.400000,100.000000,9.020000,1.000000
75%,3750.250000,127.00000,17.000000,12.000000,6.000000,3.240000,216.200000,113.000000,114.000000,19.900000,234.700000,113.000000,10.560000,2.000000
max,5000.000000,243.00000,52.000000,20.000000,20.000000,5.400000,351.500000,165.000000,170.000000,30.910000,395.000000,175.000000,17.770000,9.000000

In [ ]:
df.dtypes

Unnamed: 0          int64
state              object
area.code          object
account.length      int64
voice.plan         object
voice.messages      int64
intl.plan          object
intl.mins         float64
intl.calls          int64
intl.charge       float64
day.mins          float64
day.calls           int64
day.charge         object
eve.mins           object
eve.calls           int64
eve.charge        float64
night.mins        float64
night.calls         int64
night.charge      float64
customer.calls      int64
churn              object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      5000 non-null   int64
 1   state           5000 non-null   object
 2   area.code       5000 non-null   object
 3   account.length  5000 non-null   int64
 4   voice.plan      5000 non-null   object
 5   voice.messages  5000 non-null   int64
 6   intl.plan       5000 non-null   object
 7   intl.mins       5000 non-null   float64
 8   intl.calls      5000 non-null   int64
 9   intl.charge     5000 non-null   float64
 10  day.mins        5000 non-null   float64
 11  day.calls       5000 non-null   int64
 12  day.charge      5000 non-null   object
 13  eve.mins        5000 non-null   object
 14  eve.calls       5000 non-null   int64
 15  eve.charge      5000 non-null   float64
 16  night.mins      5000 non-null   float64
 17  night.calls     5000 non-null   int64
 18  night.charge    5000 non-null   float64
 19  customer.calls  5000 non-null   int64
 20  churn           5000 non-null   object
dtypes: float64(6), int64(8), object(7)
memory usage: 820.4+ KB

In [ ]:
#cheaching for missing values
df.isnull().sum()

Unnamed: 0        0
state             0
area.code         0
account.length    0
voice.plan        0
voice.messages    0
intl.plan         0
intl.mins         0
intl.calls        0
intl.charge       0
day.mins          0
day.calls         0
day.charge        0
eve.mins          0
eve.calls         0
eve.charge        0
night.mins        0
night.calls       0
night.charge      0
customer.calls    0
churn             0
dtype: int64

In [ ]:
df.shape

(5000, 21)

In [ ]:
sns.heatmap(df.isnull())

In [ ]:
import matplotlib.pyplot as plt
df.hist()
plt.tight_layout()

In [ ]:
df.boxplot(figsize=(18,8))

In [ ]:
numerical_col=df.select_dtypes(include=np.number).columns
print(numerical_col)


for col in numerical_col:
  sns.boxplot(x=df[col])
  plt.show()

Index(['Unnamed: 0', 'account.length', 'voice.messages', 'intl.mins',
       'intl.calls', 'intl.charge', 'day.mins', 'day.calls', 'eve.calls',
       'eve.charge', 'night.mins', 'night.calls', 'night.charge',
       'customer.calls'],
      dtype='object')

In [ ]:
summ = pd.DataFrame()
for col in numerical_col:
  summ.loc[col,'Mean'] = df[col].mean()
  summ.loc[col,'median'] = df[col].median()
  summ.loc[col,'mode'] = df[col].mode()[0]
  summ.loc[col,'std'] = df[col].std()


  q1=df[col].quantile(0.25)
  q3=df[col].quantile(0.75)
  iqr = q3-q1
  summ.loc[col,'iqr']=iqr

  summ=summ.round(2)
  display(summ)

              Mean  median  mode      std     iqr
Unnamed: 0  2500.5  2500.5   1.0  1443.52  2499.5

                   Mean  median  mode      std     iqr
Unnamed: 0      2500.50  2500.5   1.0  1443.52  2499.5
account.length   100.26   100.0  90.0    39.69    54.0

                   Mean  median  mode      std     iqr
Unnamed: 0      2500.50  2500.5   1.0  1443.52  2499.5
account.length   100.26   100.0  90.0    39.69    54.0
voice.messages     7.76     0.0   0.0    13.55    17.0

                   Mean  median  mode      std     iqr
Unnamed: 0      2500.50  2500.5   1.0  1443.52  2499.5
account.length   100.26   100.0  90.0    39.69    54.0
voice.messages     7.76     0.0   0.0    13.55    17.0
intl.mins         10.26    10.3  11.1     2.76     3.5

                   Mean  median  mode      std     iqr
Unnamed: 0      2500.50  2500.5   1.0  1443.52  2499.5
account.length   100.26   100.0  90.0    39.69    54.0
voice.messages     7.76     0.0   0.0    13.55    17.0
intl.mins         10.26    10.3  11.1     2.76     3.5
intl.calls         4.44     4.0   3.0     2.46     3.0

                   Mean   median  mode      std      iqr
Unnamed: 0      2500.50  2500.50   1.0  1443.52  2499.50
account.length   100.26   100.00  90.0    39.69    54.00
voice.messages     7.76     0.00   0.0    13.55    17.00
intl.mins         10.26    10.30  11.1     2.76     3.50
intl.calls         4.44     4.00   3.0     2.46     3.00
intl.charge        2.77     2.78   3.0     0.75     0.94

                   Mean   median   mode      std      iqr
Unnamed: 0      2500.50  2500.50    1.0  1443.52  2499.50
account.length   100.26   100.00   90.0    39.69    54.00
voice.messages     7.76     0.00    0.0    13.55    17.00
intl.mins         10.26    10.30   11.1     2.76     3.50
intl.calls         4.44     4.00    3.0     2.46     3.00
intl.charge        2.77     2.78    3.0     0.75     0.94
day.mins         180.29   180.10  154.0    53.89    72.50

                   Mean   median   mode      std      iqr
Unnamed: 0      2500.50  2500.50    1.0  1443.52  2499.50
account.length   100.26   100.00   90.0    39.69    54.00
voice.messages     7.76     0.00    0.0    13.55    17.00
intl.mins         10.26    10.30   11.1     2.76     3.50
intl.calls         4.44     4.00    3.0     2.46     3.00
intl.charge        2.77     2.78    3.0     0.75     0.94
day.mins         180.29   180.10  154.0    53.89    72.50
day.calls        100.03   100.00  105.0    19.83    26.00

                   Mean   median   mode      std      iqr
Unnamed: 0      2500.50  2500.50    1.0  1443.52  2499.50
account.length   100.26   100.00   90.0    39.69    54.00
voice.messages     7.76     0.00    0.0    13.55    17.00
intl.mins         10.26    10.30   11.1     2.76     3.50
intl.calls         4.44     4.00    3.0     2.46     3.00
intl.charge        2.77     2.78    3.0     0.75     0.94
day.mins         180.29   180.10  154.0    53.89    72.50
day.calls        100.03   100.00  105.0    19.83    26.00
eve.calls        100.19   100.00  105.0    19.83    27.00

                   Mean   median    mode      std      iqr
Unnamed: 0      2500.50  2500.50    1.00  1443.52  2499.50
account.length   100.26   100.00   90.00    39.69    54.00
voice.messages     7.76     0.00    0.00    13.55    17.00
intl.mins         10.26    10.30   11.10     2.76     3.50
intl.calls         4.44     4.00    3.00     2.46     3.00
intl.charge        2.77     2.78    3.00     0.75     0.94
day.mins         180.29   180.10  154.00    53.89    72.50
day.calls        100.03   100.00  105.00    19.83    26.00
eve.calls        100.19   100.00  105.00    19.83    27.00
eve.charge        17.05    17.09   14.25     4.30     5.76

                   Mean   median    mode      std      iqr
Unnamed: 0      2500.50  2500.50    1.00  1443.52  2499.50
account.length   100.26   100.00   90.00    39.69    54.00
voice.messages     7.76     0.00    0.00    13.55    17.00
intl.mins         10.26    10.30   11.10     2.76     3.50
intl.calls         4.44     4.00    3.00     2.46     3.00
intl.charge        2.77     2.78    3.00     0.75     0.94
day.mins         180.29   180.10  154.00    53.89    72.50
day.calls        100.03   100.00  105.00    19.83    26.00
eve.calls        100.19   100.00  105.00    19.83    27.00
eve.charge        17.05    17.09   14.25     4.30     5.76
night.mins       200.39   200.40  186.20    50.53    67.80

                   Mean   median    mode      std      iqr
Unnamed: 0      2500.50  2500.50    1.00  1443.52  2499.50
account.length   100.26   100.00   90.00    39.69    54.00
voice.messages     7.76     0.00    0.00    13.55    17.00
intl.mins         10.26    10.30   11.10     2.76     3.50
intl.calls         4.44     4.00    3.00     2.46     3.00
intl.charge        2.77     2.78    3.00     0.75     0.94
day.mins         180.29   180.10  154.00    53.89    72.50
day.calls        100.03   100.00  105.00    19.83    26.00
eve.calls        100.19   100.00  105.00    19.83    27.00
eve.charge        17.05    17.09   14.25     4.30     5.76
night.mins       200.39   200.40  186.20    50.53    67.80
night.calls       99.92   100.00  105.00    19.96    26.00

                   Mean   median    mode      std      iqr
Unnamed: 0      2500.50  2500.50    1.00  1443.52  2499.50
account.length   100.26   100.00   90.00    39.69    54.00
voice.messages     7.76     0.00    0.00    13.55    17.00
intl.mins         10.26    10.30   11.10     2.76     3.50
intl.calls         4.44     4.00    3.00     2.46     3.00
intl.charge        2.77     2.78    3.00     0.75     0.94
day.mins         180.29   180.10  154.00    53.89    72.50
day.calls        100.03   100.00  105.00    19.83    26.00
eve.calls        100.19   100.00  105.00    19.83    27.00
eve.charge        17.05    17.09   14.25     4.30     5.76
night.mins       200.39   200.40  186.20    50.53    67.80
night.calls       99.92   100.00  105.00    19.96    26.00
night.charge       9.02     9.02    8.47     2.27     3.05

                   Mean   median    mode      std      iqr
Unnamed: 0      2500.50  2500.50    1.00  1443.52  2499.50
account.length   100.26   100.00   90.00    39.69    54.00
voice.messages     7.76     0.00    0.00    13.55    17.00
intl.mins         10.26    10.30   11.10     2.76     3.50
intl.calls         4.44     4.00    3.00     2.46     3.00
intl.charge        2.77     2.78    3.00     0.75     0.94
day.mins         180.29   180.10  154.00    53.89    72.50
day.calls        100.03   100.00  105.00    19.83    26.00
eve.calls        100.19   100.00  105.00    19.83    27.00
eve.charge        17.05    17.09   14.25     4.30     5.76
night.mins       200.39   200.40  186.20    50.53    67.80
night.calls       99.92   100.00  105.00    19.96    26.00
night.charge       9.02     9.02    8.47     2.27     3.05
customer.calls     1.57     1.00    1.00     1.31     1.00

In [ ]:
for col in numerical_col:
  sns.histplot(x=df[col], kde=True)
  plt.title(f'Histogram of {col}')
  plt.show()

In [ ]:
df_no_outliers = df.copy() # creating a copy data set of original dataframe and assigns it to a new dataframe to avoid modifying the original data directly.
initial_shape = df_no_outliers.shape
print(f"Initial shape of the DataFrame: {initial_shape}")

for col in numerical_col: # start loop and removal of outlier applied only to numerical columns.
    Q1 = df_no_outliers[col].quantile(0.25)
    Q3 = df_no_outliers[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Remove outliers keeping rows where the value in the current col is within the calculated lower_bound and upper_bound
    df_no_outliers = df_no_outliers[(df_no_outliers[col] >= lower_bound) & (df_no_outliers[col] <= upper_bound)]

final_shape = df_no_outliers.shape
print(f"Shape of the DataFrame after outlier removal: {final_shape}")

# Display descriptive statistics of the new DataFrame to confirm changes
display(df_no_outliers.describe())

Initial shape of the DataFrame: (5000, 21)
Shape of the DataFrame after outlier removal: (4145, 21)

,Unnamed: 0,account.length,voice.messages,intl.mins,intl.calls,intl.charge,day.mins,day.calls,eve.calls,eve.charge,night.mins,night.calls,night.charge,customer.calls
count,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000
mean,2508.528830,99.588420,7.360434,10.314041,4.270929,2.785315,180.271218,99.998794,100.129795,17.059021,200.527575,99.805549,9.023848,1.316767
std,1434.664365,39.176513,13.009403,2.554327,2.069307,0.689581,52.401430,19.220757,19.220024,4.158313,48.813165,19.187912,2.196610,0.977681
min,1.000000,1.000000,0.000000,3.500000,1.000000,0.950000,35.100000,48.000000,48.000000,5.610000,67.100000,48.000000,3.020000,0.000000
25%,1281.000000,73.000000,0.000000,8.600000,3.000000,2.320000,143.900000,87.000000,87.000000,14.200000,167.400000,87.000000,7.530000,1.000000
50%,2507.000000,100.000000,0.000000,10.400000,4.000000,2.810000,180.000000,100.000000,100.000000,17.090000,200.200000,100.000000,9.010000,1.000000
75%,3745.000000,126.000000,15.000000,12.000000,5.000000,3.240000,216.000000,113.000000,113.000000,19.870000,234.700000,113.000000,10.560000,2.000000
max,4999.000000,205.000000,42.000000,17.100000,10.000000,4.620000,325.500000,152.000000,152.000000,28.400000,334.700000,152.000000,15.060000,3.000000

In [ ]:
df_no_outliers.boxplot(figsize=(18,8))

Still there are otliers in the data so we will use capping method to remove them .

In [ ]:
for col in df_no_outliers.select_dtypes(include=np.number).columns:
  q1=df_no_outliers[col].quantile(0.25)
  q3=df_no_outliers[col].quantile(0.75)
  iqr=q3-q1

  lower_bound=q1-1.5*iqr
  upper_bound=q3+1.5*iqr

#capping all the column value which is less then lower_bound value are replce by the lower_bound itself.
#capping all the colume value which are greater that the upper_bound value are replac by the upper bound itself.
  df_no_outliers[col]=np.where(df_no_outliers[col]<lower_bound,lower_bound,df_no_outliers[col])
  df_no_outliers[col]=np.where(df_no_outliers[col]>upper_bound,upper_bound,df_no_outliers[col])

print("outlier capped succesfully using iqr method.")

outlier capped succesfully using iqr method.

In [ ]:
df_no_outliers.boxplot(figsize=(15,12))

In [ ]:
shaped= df_no_outliers.shape
print(f"shape of new df_no_outliers:{shaped}")

shape of new df_no_outliers:(4145, 21)

In [ ]:
sns.pairplot(df_no_outliers, height=2.5, aspect=1.2)
plt.show()

###From the scatter plots we can see the correlation batween day.charge and day.mins, or intl.charge and intl.mins.

In [ ]:
df_no_outliers.corr(numeric_only=True)

,Unnamed: 0,account.length,voice.messages,intl.mins,intl.calls,intl.charge,day.mins,day.calls,eve.calls,eve.charge,night.mins,night.calls,night.charge,customer.calls
Unnamed: 0,1.000000,-0.009611,-0.048094,0.006289,-0.017140,0.006282,0.004237,-0.040539,0.012038,-0.011123,-0.011915,-0.004671,-0.011874,0.013495
account.length,-0.009611,1.000000,-0.016611,0.016249,0.017718,0.016236,-0.011491,0.028733,0.019253,-0.010632,-0.004768,0.001635,-0.004783,-0.009914
voice.messages,-0.048094,-0.016611,1.000000,0.002931,-0.019677,0.002977,0.017837,0.001706,-0.007175,0.020349,0.004560,-0.003036,0.004562,-0.012169
intl.mins,0.006289,0.016249,0.002931,1.000000,-0.005591,0.999991,-0.017467,0.001328,-0.004186,0.000488,-0.007912,0.002401,-0.007909,-0.009241
intl.calls,-0.017140,0.017718,-0.019677,-0.005591,1.000000,-0.005469,-0.006413,0.014942,0.000071,0.011461,-0.008383,-0.003495,-0.008351,0.009092
intl.charge,0.006282,0.016236,0.002977,0.999991,-0.005469,1.000000,-0.017441,0.001405,-0.004183,0.000517,-0.007869,0.002384,-0.007866,-0.009341
day.mins,0.004237,-0.011491,0.017837,-0.017467,-0.006413,-0.017441,1.000000,0.011021,0.001777,-0.008662,0.009223,-0.010010,0.009206,-0.006525
day.calls,-0.040539,0.028733,0.001706,0.001328,0.014942,0.001405,0.011021,1.000000,0.017862,0.008881,0.008914,0.003548,0.008917,-0.024443
eve.calls,0.012038,0.019253,-0.007175,-0.004186,0.000071,-0.004183,0.001777,0.017862,1.000000,-0.005430,0.018318,-0.015201,0.018362,0.001433
eve.charge,-0.011123,-0.010632,0.020349,0.000488,0.011461,0.000517,-0.008662,0.008881,-0.005430,1.000000,-0.020574,0.003451,-0.020592,-0.030771
night.mins,-0.011915,-0.004768,0.004560,-0.007912,-0.008383,-0.007869,0.009223,0.008914,0.018318,-0.020574,1.000000,0.014351,0.999999,-0.012454
night.calls,-0.004671,0.001635,-0.003036,0.002401,-0.003495,0.002384,-0.010010,0.003548,-0.015201,0.003451,0.014351,1.000000,0.014323,0.010359
night.charge,-0.011874,-0.004783,0.004562,-0.007909,-0.008351,-0.007866,0.009206,0.008917,0.018362,-0.020592,0.999999,0.014323,1.000000,-0.012456
customer.calls,0.013495,-0.009914,-0.012169,-0.009241,0.009092,-0.009341,-0.006525,-0.024443,0.001433,-0.030771,-0.012454,0.010359,-0.012456,1.000000

In [ ]:
plt.figure(figsize=(10,8))
sns.heatmap(df_no_outliers.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.show()

In [ ]:
df_no_outliers.head()

,Unnamed: 0,state,area.code,account.length,voice.plan,voice.messages,intl.plan,intl.mins,intl.calls,intl.charge,...,day.calls,day.charge,eve.mins,eve.calls,eve.charge,night.mins,night.calls,night.charge,customer.calls,churn
0,1.0,KS,area_code_415,128.0,yes,25.0,no,10.0,3.0,2.70,...,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,1.0,no
1,2.0,OH,area_code_415,107.0,yes,26.0,no,13.7,3.0,3.70,...,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,1.0,no
2,3.0,NJ,area_code_415,137.0,no,0.0,no,12.2,5.0,3.29,...,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,0.0,no
4,5.0,OK,area_code_415,75.0,no,0.0,yes,10.1,3.0,2.73,...,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,3.0,no
5,6.0,AL,area_code_510,118.0,no,0.0,yes,6.3,6.0,1.70,...,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,0.0,no

In [ ]:
#converting categorical columns into numerical columns

df_no_outliers = pd.get_dummies(data=df_no_outliers,
                                columns=['state', 'area.code', 'voice.plan',
                                         'intl.plan', 'day.charge', 'eve.mins', 'churn'])

In [ ]:
df_no_outliers.head()

,Unnamed: 0,account.length,voice.messages,intl.mins,intl.calls,intl.charge,day.mins,day.calls,eve.calls,eve.charge,...,eve.mins_328.2,eve.mins_328.7,eve.mins_329.8,eve.mins_330.6,eve.mins_332.1,eve.mins_332.3,eve.mins_334.1,eve.mins_Nan,churn_no,churn_yes
0,1.0,128.0,25.0,10.0,3.0,2.70,265.1,110.0,99.0,16.78,...,False,False,False,False,False,False,False,False,True,False
1,2.0,107.0,26.0,13.7,3.0,3.70,161.6,123.0,103.0,16.62,...,False,False,False,False,False,False,False,False,True,False
2,3.0,137.0,0.0,12.2,5.0,3.29,243.4,114.0,110.0,10.30,...,False,False,False,False,False,False,False,False,True,False
4,5.0,75.0,0.0,10.1,3.0,2.73,166.7,113.0,122.0,12.61,...,False,False,False,False,False,False,False,False,True,False
5,6.0,118.0,0.0,6.3,6.0,1.70,223.4,98.0,101.0,18.75,...,False,False,False,False,False,False,False,False,True,False

In [ ]:
#Scaling the data bring down all columns to same scale
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [ ]:
mn=MinMaxScaler()
df_no_outliers.columns

Index(['Unnamed: 0', 'account.length', 'voice.messages', 'intl.mins',
       'intl.calls', 'intl.charge', 'day.mins', 'day.calls', 'eve.calls',
       'eve.charge',
       ...
       'eve.mins_328.2', 'eve.mins_328.7', 'eve.mins_329.8', 'eve.mins_330.6',
       'eve.mins_332.1', 'eve.mins_332.3', 'eve.mins_334.1', 'eve.mins_Nan',
       'churn_no', 'churn_yes'],
      dtype='object', length=3606)

In [ ]:
minmax_scale = pd.DataFrame(mn.fit_transform(df_no_outliers), columns=df_no_outliers.columns)

### Correlation of Features with Target Variable (`churn_yes`)

Let's check the correlation of all features in the `minmax_scale` DataFrame with our target variable `churn_yes` to identify features that might be strong predictors of churn. We are choshing churn as the target variable beacuse it directly indicate whether a customer has stopped using a service.

In [ ]:
correlations = minmax_scale.corrwith(minmax_scale['churn_yes']).sort_values(ascending=False)

print("Top 10 features positively correlated with churn_yes:")
display(correlations.head(10))

print("\nTop 10 features negatively correlated with churn_yes:")
display(correlations.tail(10))

plt.figure(figsize=(10, 6))
correlations_plot = correlations.drop('churn_yes').plot(kind='bar', figsize=(20, 7), color='skyblue')
plt.title('Correlation of Features with Churn (churn_yes)')
plt.xlabel('Features')
plt.ylabel('Correlation Coefficient')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

Top 10 features positively correlated with churn_yes:

churn_yes           1.000000
day.mins            0.297167
intl.plan_yes       0.281960
eve.charge          0.132969
voice.plan_no       0.105412
eve.mins_205.7      0.078394
day.charge_45.54    0.078394
intl.mins           0.068827
intl.charge         0.068825
night.mins          0.067541
dtype: float64

Top 10 features negatively correlated with churn_yes:

state_NE         -0.023027
state_AK         -0.023385
state_LA         -0.026246
state_VA         -0.027975
state_WI         -0.031187
intl.calls       -0.062601
voice.messages   -0.095668
voice.plan_yes   -0.105412
intl.plan_no     -0.281960
churn_no         -1.000000
dtype: float64

In [ ]:
#feature engineering

### Feature Engineering: Creating Aggregate Features

We will create new features by summing up related call minutes, call counts, and charges across different periods (day, evening, night, international). This helps in reducing dimensionality and potentially capturing more meaningful patterns from customer behavior.

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Create new aggregated features
# Note: 'eve.mins' and 'day.charge' were one-hot encoded, so we can't sum them directly as numerical values.
# We will use the original numerical minute/call/charge columns available in df_no_outliers.

# Total call minutes (excluding 'eve.mins' as it's one-hot encoded)
df_no_outliers['total_call_minutes'] = df_no_outliers['day.mins'] + \
                                        df_no_outliers['night.mins'] + \
                                        df_no_outliers['intl.mins']

# Total calls made
df_no_outliers['total_calls_made'] = df_no_outliers['day.calls'] + \
                                      df_no_outliers['eve.calls'] + \
                                      df_no_outliers['night.calls'] + \
                                      df_no_outliers['intl.calls'] + \
                                      df_no_outliers['customer.calls']

# Total charge cost (excluding 'day.charge' as it's one-hot encoded)
df_no_outliers['total_charge_cost'] = df_no_outliers['intl.charge'] + \
                                       df_no_outliers['eve.charge'] + \
                                       df_no_outliers['night.charge']

# Display the first few rows with new features
print("DataFrame with new engineered features:")
display(df_no_outliers[['day.mins', 'night.mins', 'intl.mins', 'total_call_minutes',
                        'day.calls', 'eve.calls', 'night.calls', 'intl.calls', 'customer.calls', 'total_calls_made',
                        'intl.charge', 'eve.charge', 'night.charge', 'total_charge_cost']].head())

DataFrame with new engineered features:

,day.mins,night.mins,intl.mins,total_call_minutes,day.calls,eve.calls,night.calls,intl.calls,customer.calls,total_calls_made,intl.charge,eve.charge,night.charge,total_charge_cost
0,265.1,244.7,10.0,519.8,110.0,99.0,91.0,3.0,1.0,304.0,2.70,16.78,11.01,30.49
1,161.6,254.4,13.7,429.7,123.0,103.0,103.0,3.0,1.0,333.0,3.70,16.62,11.45,31.77
2,243.4,162.6,12.2,418.2,114.0,110.0,104.0,5.0,0.0,333.0,3.29,10.30,7.32,20.91
4,166.7,186.9,10.1,363.7,113.0,122.0,121.0,3.0,3.0,362.0,2.73,12.61,8.41,23.75
5,223.4,203.9,6.3,433.6,98.0,101.0,118.0,6.0,0.0,323.0,1.70,18.75,9.18,29.63

### Re-scaling the DataFrame after Feature Engineering

Since we've added new features, we need to re-apply Min-Max scaling to the entire `df_no_outliers` DataFrame to ensure all features remain on a consistent scale (0 to 1).

In [ ]:
# Initialize MinMaxScaler
mn = MinMaxScaler()

# Apply Min-Max Scaling to the entire DataFrame including the new features
minmax_scale_fe = pd.DataFrame(mn.fit_transform(df_no_outliers), columns=df_no_outliers.columns)

# Display the first few rows of the re-scaled DataFrame
print("Re-scaled DataFrame with new engineered features (minmax_scale_fe):")
display(minmax_scale_fe.head())

print(f"New shape of the DataFrame after feature engineering and re-scaling: {minmax_scale_fe.shape}")

Re-scaled DataFrame with new engineered features (minmax_scale_fe):

,Unnamed: 0,account.length,voice.messages,intl.mins,intl.calls,intl.charge,day.mins,day.calls,eve.calls,eve.charge,...,eve.mins_330.6,eve.mins_332.1,eve.mins_332.3,eve.mins_334.1,eve.mins_Nan,churn_no,churn_yes,total_call_minutes,total_calls_made,total_charge_cost
0,0.0000,0.622549,0.666667,0.477941,0.285714,0.476839,0.795250,0.596154,0.490385,0.488757,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.780541,0.513761,0.584424
1,0.0002,0.519608,0.693333,0.750000,0.285714,0.749319,0.436373,0.721154,0.528846,0.481702,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.585730,0.646789,0.626309
2,0.0004,0.666667,0.000000,0.639706,0.571429,0.637602,0.720007,0.634615,0.596154,0.203042,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.560865,0.646789,0.270942
3,0.0008,0.362745,0.000000,0.485294,0.285714,0.485014,0.454057,0.625000,0.711538,0.304894,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.443027,0.779817,0.363874
4,0.0010,0.573529,0.000000,0.205882,0.714286,0.204360,0.650659,0.480769,0.509615,0.575617,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.594162,0.600917,0.556283

New shape of the DataFrame after feature engineering and re-scaling: (4145, 3609)

### Features with the strongest correlation to `churn_yes`

In [ ]:
print("Features with the strongest positive correlation to 'churn_yes':")
display(correlations.head(5))

print("\nFeatures with the strongest negative correlation to 'churn_yes':")
display(correlations.tail(5))

Features with the strongest positive correlation to 'churn_yes':

churn_yes        1.000000
day.mins         0.297167
intl.plan_yes    0.281960
eve.charge       0.132969
voice.plan_no    0.105412
dtype: float64

Features with the strongest negative correlation to 'churn_yes':

intl.calls       -0.062601
voice.messages   -0.095668
voice.plan_yes   -0.105412
intl.plan_no     -0.281960
churn_no         -1.000000
dtype: float64

##MODEL BUILDING AND MODEL EVALUTION

### Data Preparation for Modeling: Feature Selection and Data Splitting

Before building any model, we need to prepare our data. This involves:
1.  **Defining Features (X) and Target (y):** Our target variable is `churn_yes`, and all other relevant columns will be our features.
2.  **Splitting the Data:** We'll divide the dataset into training and testing sets to evaluate the model's performance on unseen data. A common split is 70-80% for training and 20-30% for testing.

In [ ]:
# Define features (X) and target (y)
X = minmax_scale_fe.drop(['churn_no', 'churn_yes'], axis=1)
y = minmax_scale_fe['churn_yes']

print(f"Shape of features (X): {X.shape}")
print(f"Shape of target (y): {y.shape}")

Shape of features (X): (4145, 3607)
Shape of target (y): (4145,)

In [ ]:
from sklearn.model_selection import train_test_split,cross_val_score

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (3316, 3607)
X_test shape: (829, 3607)
y_train shape: (3316,)
y_test shape: (829,)

In [ ]:
plt.scatter(df_no_outliers['day.mins'], df_no_outliers['night.mins'], c=df_no_outliers['churn_yes'])
plt.xlabel('day.mins')
plt.ylabel('night.mins')
plt.show()

### Model Selection for Churn Prediction

Given that this is a **binary classification problem** (predicting whether a customer will churn or not), several machine learning models are suitable. Here are some common choices:

1.**Logistic Regression:** A simple yet effective linear model for binary classification. It's a good baseline and offers interpretability.

2.**Support Vector Machines (SVM):** Effective in high-dimensional spaces and cases where the number of dimensions is greater than the number of samples.

3.**Decision Trees:** Can capture non-linear relationships and are easy to interpret (if the tree is not too deep).

4.**Random Forest:** An ensemble method based on decision trees. It often provides higher accuracy and is more robust to overfitting than single decision trees.

5.**K-Nearest Neighbors (KNN):** A simple, non-parametric algorithm that classifies data points based on the majority class of its nearest neighbors.

6.**Gradient Boosting Machines (e.g., XGBoost, LightGBM):** Highly powerful ensemble methods that often achieve state-of-the-art performance in classification tasks.

Let's start by implementing **Logistic Regression** as a first model, as it's a good starting point for classification problems due to its simplicity and interpretability.

In [ ]:
#logistic regression
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)

LogisticRegression()

In [ ]:
from sklearn.metrics import accuracy_score

y_tain_pred = log_reg.predict(X_train)
y_test_pred = log_reg.predict(X_test)

train_accuracy = accuracy_score(y_train, y_tain_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

#printing the accuracy scores

print(f"Train Accuracy:{train_accuracy}")
print(f"Test Accuracy:{test_accuracy}")

Train Accuracy:0.9490349819059107
Test Accuracy:0.9191797346200241

In [ ]:
#SVM (Support vector machines) ,maximum marginal classifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV , RandomizedSearchCV ,KFold ,cross_val_score
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score , confusion_matrix

In [ ]:
#model building
clf=SVC(kernel='rbf',gamma=0.001)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
acc=accuracy_score(y_test,y_pred)*100
print("Accuracy=",acc)
confusion_matrix(y_test,y_pred)

Accuracy= 89.50542822677924

array([[742,   0],
       [ 87,   0]])

In [ ]:
num_folds=10
kfold=KFold(n_splits=num_folds)

In [ ]:
#Grid searchCV for hyperparameter tuning
clf=SVC()
param_grid={'kernel':['rbf'], 'gamma':[0.001,0.01,0.1,1,10]}
grid_search=GridSearchCV(clf,param_grid=param_grid,cv=kfold,)
grid_search.fit(X_train,y_train)

GridSearchCV(cv=KFold(n_splits=10, random_state=None, shuffle=False),
             estimator=SVC(),
             param_grid={'gamma': [0.001, 0.01, 0.1, 1, 10], 'kernel': ['rbf']})

In [ ]:
grid_search.best_params_,grid_search.best_score_

({'gamma': 0.001, 'kernel': 'rbf'}, np.float64(0.8944545553816475))

In [ ]:
clf=SVC(C=10,gamma=0.001,kernel='rbf')
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
acc=accuracy_score(y_test,y_pred)*100
print("Accuracy=",acc)
confusion_matrix(y_test,y_pred)

Accuracy= 89.50542822677924

array([[742,   0],
       [ 87,   0]])

In [ ]:
# Decision Tree
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

model=DecisionTreeClassifier(criterion='entropy',max_depth=2,random_state=0)
model.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=2, random_state=0)

In [ ]:
#plot the decision tree
tree.plot_tree(model)
plt.show()

In [ ]:
fn=X_train.columns
cn=['No Churn', 'Churn'] # Assuming 0 represents 'No Churn' and 1 represents 'Churn'
tree.plot_tree(model,feature_names=fn,class_names=cn,filled=True);

In [ ]:
pred=model.predict(X_test)
pd.Series(pred).value_counts()

0.0    767
1.0     62
Name: count, dtype: int64

In [ ]:
pd.crosstab(y_test,pred)

col_0      0.0  1.0
churn_yes
0.0        715   27
1.0         52   35

In [ ]:
#accuracy
np.mean(pred==y_test)
print(f"desicion tree model accuracy:{np.mean(pred==y_test)}")

desicion tree model accuracy:0.9047044632086851

In [ ]:
# Random Forest

from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier

In [209]:
# Initialize RandomForestClassifier
rf_model = RandomForestClassifier(random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [212]:
# Make predictions on the test set
y_pred_rf = rf_model.predict(X_test)

In [214]:
# Evaluate the model
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Accuracy: {accuracy_rf:}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 0.9288299155609168

Classification Report:
              precision    recall  f1-score   support

         0.0       0.93      1.00      0.96       742
         1.0       1.00      0.32      0.49        87

    accuracy                           0.93       829
   macro avg       0.96      0.66      0.72       829
weighted avg       0.93      0.93      0.91       829

In [237]:
# K Nearest Neighbours
from sklearn.neighbors import KNeighborsClassifier
num_folds=10
kfold = KFold(n_splits=num_folds)

In [238]:
model = KNeighborsClassifier(n_neighbors=5)
result = cross_val_score(model, X, y, cv=kfold, scoring='accuracy')
print(result.mean())

0.8928805075373958

In [244]:
x=(X-X.min())/(X.max()-X.min())

In [250]:
n_neighbors=np.array([2*i+1 for i in range(0,20)])

In [248]:
param_grid=dict(n_neighbors=n_neighbors)

In [251]:
param_grid

{'n_neighbors': array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39])}

In [252]:
n_neighbors

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [253]:
model=KNeighborsClassifier()
grid=GridSearchCV(estimator=model,param_grid=param_grid)
grid.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])})

In [254]:
print(grid.best_score_)
print(grid.best_params_) # FOR CALCULATING THE VALUE OF K

0.8986725181268058
{'n_neighbors': np.int64(9)}

In [261]:
K_range=range(1,9)
K_scores=[]

for k in K_range:
  knn= KNeighborsClassifier(n_neighbors=k)
  scores=cross_val_score(knn,X,y,cv=kfold,scoring='accuracy')
  K_scores.append(scores.mean())
pd.Series(K_scores).sort_values(ascending=False)

7    0.896979
5    0.894810
6    0.894570
3    0.894568
4    0.892881
1    0.892637
2    0.888536
0    0.861755
dtype: float64

In [281]:
import matplotlib.pyplot as plt
plt.plot(K_range,K_scores)
plt.xlabel('Value of K for KNN')
plt.ylabel('Cross-Validated Accuracy')
plt.show()

In [295]:
# Install XGBoost if you haven't already
!pip install xgboost

# Import XGBoost classifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)
XGBoost installed and imported successfully!

In [296]:
# Initialize XGBoost Classifier
# Using 'objective='binary:logistic'' for binary classification and 'eval_metric='logloss'' for evaluation
xgb_model = XGBClassifier(objective='binary:logistic', eval_metric='logloss', use_label_encoder=False, random_state=42)

# Train the model
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [293]:
# Make predictions on the test set
y_pred_xgb = xgb_model.predict(X_test)

# Evaluate the model
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print(f"XGBoost Accuracy: {accuracy_xgb:}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

XGBoost Accuracy: 0.9783

Classification Report:
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99       742
         1.0       0.99      0.80      0.89        87

    accuracy                           0.98       829
   macro avg       0.98      0.90      0.94       829
weighted avg       0.98      0.98      0.98       829

In [300]:
from sklearn.metrics import accuracy_score

# Logistic Regression
log_reg_test_accuracy = 0.9191797346200241

# SVM
svm_test_accuracy = 0.8950542822677924

# Decision Tree
dt_test_accuracy = 0.9047044632086851

# Random Forest
rf_test_accuracy = 0.9288299155609168

# KNN (using best_score_ from GridSearchCV  )
knn_test_accuracy = 0.8986725181268058

#XGBoost
accuracy_xgb = 0.9782870928829915

# Create a dictionary to store model accuracies
model_accuracies = {
    'Logistic Regression': log_reg_test_accuracy,
    'SVM': svm_test_accuracy,
    'Decision Tree': dt_test_accuracy,
    'Random Forest': rf_test_accuracy,
    'K-Nearest Neighbors': knn_test_accuracy,
    'XGBoost': accuracy_xgb
}

# Convert to a pandas Series for easy comparison and display
accuracies_series = pd.Series(model_accuracies).sort_values(ascending=False)

print("Model Test Accuracies:")
display(accuracies_series)

best_model = accuracies_series.index[0]
best_accuracy = accuracies_series.iloc[0]

print(f"\nThe most accurate model is '{best_model}' with a test accuracy of {best_accuracy:.4f}.")

Model Test Accuracies:

XGBoost                0.978287
Random Forest          0.928830
Logistic Regression    0.919180
Decision Tree          0.904704
K-Nearest Neighbors    0.898673
SVM                    0.895054
dtype: float64

The most accurate model is 'XGBoost' with a test accuracy of 0.9783.

# Conclusion.
Based on our evaluation, **XGBoost emerged as the most accurate model** for predicting customer churn in this dataset. Its strong performance highlights the effectiveness of gradient boosting techniques for complex classification tasks.